# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65e934c09322551bdd5d77ad8258837c5d841424244ee5cbaca5e6bc1c30cd9acbd0a3904fb51adcfff06ce68049b04fb7102656499ce3b130de0016988cf86d

test:
  secret_key_base: cd6ab2653ba2571c7e8ab3b79ae0ab0a670b5ab6ac51805982d58b9478293adb035271e420c5d3a6a265ec5a8ba5339e0a49d33a7d41e9bd7bb00d1b8a64b07f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
